// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LED

#include "../ui.h"

void ui_Index_screen_init(void)
{
    ui_Index = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Index, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Body = lv_obj_create(ui_Index);
    lv_obj_remove_style_all(ui_Body);
    lv_obj_set_width(ui_Body, lv_pct(100));
    lv_obj_set_height(ui_Body, lv_pct(100));
    lv_obj_set_align(ui_Body, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Body, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Body, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Body, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Menu_Box = lv_obj_create(ui_Body);
    lv_obj_set_width(ui_Menu_Box, 80);
    lv_obj_set_height(ui_Menu_Box, lv_pct(100));
    lv_obj_set_x(ui_Menu_Box, 2);
    lv_obj_set_y(ui_Menu_Box, -32);
    lv_obj_set_align(ui_Menu_Box, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Menu_Box, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Menu_Box, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Menu_Box, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Menu_Box, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Menu_Box, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Menu_Box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Menu_Box, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Home_btn = lv_btn_create(ui_Menu_Box);
    lv_obj_set_width(ui_Home_btn, 70);
    lv_obj_set_height(ui_Home_btn, 70);
    lv_obj_set_x(ui_Home_btn, 1);
    lv_obj_set_y(ui_Home_btn, -133);
    lv_obj_set_align(ui_Home_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Home_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Home_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Home_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Home_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Home_btn, &ui_img_685164422, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Home_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Home_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Home_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Home_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_src(ui_Home_btn, &ui_img_685164422, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Home_btn, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Home_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_switch_btn = lv_btn_create(ui_Menu_Box);
    lv_obj_set_width(ui_switch_btn, 70);
    lv_obj_set_height(ui_switch_btn, 70);
    lv_obj_set_x(ui_switch_btn, -1);
    lv_obj_set_y(ui_switch_btn, -19);
    lv_obj_set_align(ui_switch_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_switch_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_switch_btn, &ui_img_alarm_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_switch_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_switch_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_switch_btn, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_switch_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Pill_btn = lv_btn_create(ui_Menu_Box);
    lv_obj_set_width(ui_Pill_btn, 70);
    lv_obj_set_height(ui_Pill_btn, 70);
    lv_obj_set_x(ui_Pill_btn, -1);
    lv_obj_set_y(ui_Pill_btn, -19);
    lv_obj_set_align(ui_Pill_btn, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Pill_btn, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Pill_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Pill_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Pill_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Pill_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Pill_btn, &ui_img_pill_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Pill_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Pill_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Pill_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Pill_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Pill_btn, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Pill_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Setting_btn = lv_btn_create(ui_Menu_Box);
    lv_obj_set_width(ui_Setting_btn, 70);
    lv_obj_set_height(ui_Setting_btn, 70);
    lv_obj_set_x(ui_Setting_btn, -1);
    lv_obj_set_y(ui_Setting_btn, -19);
    lv_obj_set_align(ui_Setting_btn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Setting_btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Setting_btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting_btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Setting_btn, &ui_img_setting_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Setting_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Setting_btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting_btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Setting_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor(ui_Setting_btn, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_img_recolor_opa(ui_Setting_btn, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Main = lv_obj_create(ui_Body);
    lv_obj_remove_style_all(ui_Main);
    lv_obj_set_width(ui_Main, 396);
    lv_obj_set_height(ui_Main, lv_pct(99));
    lv_obj_set_x(ui_Main, 103);
    lv_obj_set_y(ui_Main, 122);
    lv_obj_set_align(ui_Main, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_Main, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_Con = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_home_Con);
    lv_obj_set_width(ui_home_Con, 395);
    lv_obj_set_height(ui_home_Con, lv_pct(86));
    lv_obj_set_x(ui_home_Con, 1);
    lv_obj_set_y(ui_home_Con, 23);
    lv_obj_set_align(ui_home_Con, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_home_Con, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_home_Con, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_home_Con, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_home_Con, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_home_Con, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_home_layout = lv_obj_create(ui_home_Con);
    lv_obj_remove_style_all(ui_home_layout);
    lv_obj_set_height(ui_home_layout, 273);
    lv_obj_set_width(ui_home_layout, lv_pct(100));
    lv_obj_set_x(ui_home_layout, 307);
    lv_obj_set_y(ui_home_layout, 5);
    lv_obj_set_align(ui_home_layout, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_home_layout, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_home_layout, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_home_layout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_status_layout = lv_obj_create(ui_home_layout);
    lv_obj_set_width(ui_status_layout, lv_pct(101));
    lv_obj_set_height(ui_status_layout, lv_pct(98));
    lv_obj_set_x(ui_status_layout, 41);
    lv_obj_set_y(ui_status_layout, 32);
    lv_obj_set_align(ui_status_layout, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_status_layout, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_status_layout, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_status_layout, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_status_layout);
    lv_obj_set_width(ui_Label3, lv_pct(100));
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Sensor Status");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label3, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_box = lv_obj_create(ui_status_layout);
    lv_obj_remove_style_all(ui_temp_box);
    lv_obj_set_width(ui_temp_box, lv_pct(101));
    lv_obj_set_height(ui_temp_box, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_box, -1);
    lv_obj_set_y(ui_temp_box, -18);
    lv_obj_set_align(ui_temp_box, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_temp_box, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_temp_box, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_temp_box, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp_Label = lv_label_create(ui_temp_box);
    lv_obj_set_width(ui_temp_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_temp_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp_Label, "อุณหภูมิ");
    lv_obj_set_style_text_font(ui_temp_Label, &ui_font_kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_temp_box);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 198);
    lv_obj_set_height(ui_Container9, 29);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp_Label_value = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_temp_Label_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_Label_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_Label_value, 265);
    lv_obj_set_y(ui_temp_Label_value, 5);
    lv_label_set_text(ui_temp_Label_value, "20.5 ");
    lv_obj_set_style_text_font(ui_temp_Label_value, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp_Label_value1 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_temp_Label_value1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_Label_value1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_Label_value1, 265);
    lv_obj_set_y(ui_temp_Label_value1, 5);
    lv_label_set_text(ui_temp_Label_value1, "°C");
    lv_obj_set_style_text_font(ui_temp_Label_value1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humi_box = lv_obj_create(ui_status_layout);
    lv_obj_remove_style_all(ui_Humi_box);
    lv_obj_set_width(ui_Humi_box, lv_pct(101));
    lv_obj_set_height(ui_Humi_box, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humi_box, -1);
    lv_obj_set_y(ui_Humi_box, -18);
    lv_obj_set_align(ui_Humi_box, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Humi_box, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Humi_box, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Humi_box, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humi_Label = lv_label_create(ui_Humi_box);
    lv_obj_set_width(ui_humi_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humi_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_humi_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humi_Label, "ความชื้น");
    lv_obj_set_style_text_font(ui_humi_Label, &ui_font_kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Humi_box);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 204);
    lv_obj_set_height(ui_Container8, 31);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_humi_Label_value = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_humi_Label_value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humi_Label_value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humi_Label_value, 265);
    lv_obj_set_y(ui_humi_Label_value, 5);
    lv_label_set_text(ui_humi_Label_value, "90.5");
    lv_obj_set_style_text_font(ui_humi_Label_value, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humi_Label_value1 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_humi_Label_value1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_humi_Label_value1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_humi_Label_value1, 265);
    lv_obj_set_y(ui_humi_Label_value1, 5);
    lv_label_set_text(ui_humi_Label_value1, "%RH");
    lv_obj_set_style_text_font(ui_humi_Label_value1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_status_layout);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(100));
    lv_obj_set_height(ui_Container1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container1, -395);
    lv_obj_set_y(ui_Container1, 513);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P_name = lv_dropdown_create(ui_Container1);
    lv_dropdown_set_options(ui_P_name, "");
    lv_obj_set_width(ui_P_name, lv_pct(84));
    lv_obj_set_height(ui_P_name, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_P_name, 1);
    lv_obj_set_y(ui_P_name, -1);
    lv_obj_set_align(ui_P_name, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P_name, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_P_name, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_P_name), &lv_font_montserrat_18,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_P_refresh = lv_btn_create(ui_Container1);
    lv_obj_set_width(ui_P_refresh, 46);
    lv_obj_set_height(ui_P_refresh, 46);
    lv_obj_set_align(ui_P_refresh, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P_refresh, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_P_refresh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_P_refresh, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P_refresh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_P_refresh, &ui_img_1626888446, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_P_refresh, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_P_refresh, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_P_refresh, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_P_refresh, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_status_layout);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Container2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch1_select1 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_switch1_select1, 40);
    lv_obj_set_height(ui_switch1_select1, 40);
    lv_obj_set_align(ui_switch1_select1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_switch1_select1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch1_select1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch1_select1, lv_color_hex(0xD4D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch1_select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_switch1_select1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_switch1_select1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_switch1_select1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch1_select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch1_select1, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch1_select1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label15 = lv_label_create(ui_switch1_select1);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "1");
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch2_select1 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_switch2_select1, 40);
    lv_obj_set_height(ui_switch2_select1, 40);
    lv_obj_set_align(ui_switch2_select1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_switch2_select1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch2_select1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch2_select1, lv_color_hex(0xD4D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch2_select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_switch2_select1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_switch2_select1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_switch2_select1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch2_select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch2_select1, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch2_select1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label16 = lv_label_create(ui_switch2_select1);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "2");
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch3_select1 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_switch3_select1, 40);
    lv_obj_set_height(ui_switch3_select1, 40);
    lv_obj_set_align(ui_switch3_select1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_switch3_select1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch3_select1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch3_select1, lv_color_hex(0xD4D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch3_select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_switch3_select1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_switch3_select1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_switch3_select1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch3_select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch3_select1, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch3_select1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label17 = lv_label_create(ui_switch3_select1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "3");
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch4_select1 = lv_btn_create(ui_Container3);
    lv_obj_set_width(ui_switch4_select1, 40);
    lv_obj_set_height(ui_switch4_select1, 40);
    lv_obj_set_align(ui_switch4_select1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_switch4_select1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_switch4_select1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch4_select1, lv_color_hex(0xD4D4D4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch4_select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_switch4_select1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_switch4_select1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_switch4_select1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_switch4_select1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_switch4_select1, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_switch4_select1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label18 = lv_label_create(ui_switch4_select1);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "4");
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switch_Con = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_switch_Con);
    lv_obj_set_width(ui_switch_Con, lv_pct(97));
    lv_obj_set_height(ui_switch_Con, lv_pct(84));
    lv_obj_set_x(ui_switch_Con, 0);
    lv_obj_set_y(ui_switch_Con, 22);
    lv_obj_set_align(ui_switch_Con, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_switch_Con, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_switch_Con, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_switch_Con, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_switch_Con, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_pill_type_box = lv_obj_create(ui_switch_Con);
    lv_obj_remove_style_all(ui_pill_type_box);
    lv_obj_set_height(ui_pill_type_box, 43);
    lv_obj_set_width(ui_pill_type_box, lv_pct(99));
    lv_obj_set_x(ui_pill_type_box, 435);
    lv_obj_set_y(ui_pill_type_box, 155);
    lv_obj_set_align(ui_pill_type_box, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_pill_type_box, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_pill_type_box, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_pill_type_box, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_pill_type_box);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -15);
    lv_obj_set_y(ui_Label5, -2);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Pill Table");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_kanit24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_type_sele = lv_obj_create(ui_pill_type_box);
    lv_obj_remove_style_all(ui_type_sele);
    lv_obj_set_width(ui_type_sele, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_type_sele, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_type_sele, -30);
    lv_obj_set_y(ui_type_sele, 107);
    lv_obj_set_align(ui_type_sele, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_type_sele, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_type_sele, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_type_sele, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_type_sele, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_type_sele, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_type_a = lv_btn_create(ui_type_sele);
    lv_obj_set_width(ui_type_a, 122);
    lv_obj_set_height(ui_type_a, 40);
    lv_obj_set_x(ui_type_a, -2);
    lv_obj_set_y(ui_type_a, 1);
    lv_obj_set_align(ui_type_a, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_type_a, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_type_a, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_type_a, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_type_a, lv_color_hex(0xB3B3B3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_type_a, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_type_a, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_type_a, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_A_Label = lv_label_create(ui_type_a);
    lv_obj_set_width(ui_A_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_A_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_A_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_A_Label, "Client Name");
    lv_obj_set_style_text_font(ui_A_Label, &ui_font_kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timer_bodyA = lv_obj_create(ui_switch_Con);
    lv_obj_remove_style_all(ui_timer_bodyA);
    lv_obj_set_width(ui_timer_bodyA, lv_pct(98));
    lv_obj_set_height(ui_timer_bodyA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timer_bodyA, 92);
    lv_obj_set_y(ui_timer_bodyA, 88);
    lv_obj_set_align(ui_timer_bodyA, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_timer_bodyA, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_timer_bodyA, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_timer_bodyA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_r12_label3 = lv_obj_create(ui_timer_bodyA);
    lv_obj_remove_style_all(ui_r12_label3);
    lv_obj_set_height(ui_r12_label3, 30);
    lv_obj_set_width(ui_r12_label3, lv_pct(100));
    lv_obj_set_align(ui_r12_label3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_r12_label3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_r12_label3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_r12_label3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_r12_label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_r12_label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_r12_label3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_r12_label3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox1A = lv_checkbox_create(ui_r12_label3);
    lv_checkbox_set_text(ui_Checkbox1A, "รอบที่ 1 ");
    lv_obj_set_width(ui_Checkbox1A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1A, -69);
    lv_obj_set_y(ui_Checkbox1A, -69);
    lv_obj_set_align(ui_Checkbox1A, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox1A, &ui_font_kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox2A = lv_checkbox_create(ui_r12_label3);
    lv_checkbox_set_text(ui_Checkbox2A, "รอบที่ 2 ");
    lv_obj_set_width(ui_Checkbox2A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2A, -69);
    lv_obj_set_y(ui_Checkbox2A, -69);
    lv_obj_set_align(ui_Checkbox2A, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox2A, &ui_font_kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_t3 = lv_obj_create(ui_timer_bodyA);
    lv_obj_remove_style_all(ui_t3);
    lv_obj_set_height(ui_t3, 49);
    lv_obj_set_width(ui_t3, lv_pct(100));
    lv_obj_set_align(ui_t3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_t3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_t3, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_t3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_t3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_t3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_t3, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_t3, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time__in1A = lv_label_create(ui_t3);
    lv_obj_set_width(ui_time__in1A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time__in1A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time__in1A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time__in1A, "00:00");
    lv_obj_add_flag(ui_time__in1A, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_time__in1A, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_time__in1A, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__in1A, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time__in1A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_time__in1A, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_time__in1A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_time__in1A, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_time__in1A, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_time__in1A, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_time__in1A, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_time__in1A, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_time__in1A, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__in1A, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_time__in1A, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_time__in1A, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_time__in1A, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_time__in2A = lv_label_create(ui_t3);
    lv_obj_set_width(ui_time__in2A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time__in2A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time__in2A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time__in2A, "00:00");
    lv_obj_add_flag(ui_time__in2A, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_time__in2A, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_time__in2A, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__in2A, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time__in2A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_time__in2A, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_time__in2A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_time__in2A, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_time__in2A, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_time__in2A, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_time__in2A, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_time__in2A, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_time__in2A, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__in2A, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_time__in2A, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_time__in2A, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_time__in2A, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_r12_label4 = lv_obj_create(ui_timer_bodyA);
    lv_obj_remove_style_all(ui_r12_label4);
    lv_obj_set_height(ui_r12_label4, 25);
    lv_obj_set_width(ui_r12_label4, lv_pct(100));
    lv_obj_set_x(ui_r12_label4, 12);
    lv_obj_set_y(ui_r12_label4, -38);
    lv_obj_set_align(ui_r12_label4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_r12_label4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_r12_label4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_r12_label4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_r12_label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_r12_label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_r12_label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_r12_label4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox3A = lv_checkbox_create(ui_r12_label4);
    lv_checkbox_set_text(ui_Checkbox3A, "รอบที่ 3 ");
    lv_obj_set_width(ui_Checkbox3A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox3A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox3A, -69);
    lv_obj_set_y(ui_Checkbox3A, -69);
    lv_obj_set_align(ui_Checkbox3A, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox3A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox3A, &ui_font_kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox4A = lv_checkbox_create(ui_r12_label4);
    lv_checkbox_set_text(ui_Checkbox4A, "รอบที่ 4 ");
    lv_obj_set_width(ui_Checkbox4A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox4A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox4A, -69);
    lv_obj_set_y(ui_Checkbox4A, -69);
    lv_obj_set_align(ui_Checkbox4A, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox4A, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Checkbox4A, &ui_font_kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_t4 = lv_obj_create(ui_timer_bodyA);
    lv_obj_remove_style_all(ui_t4);
    lv_obj_set_height(ui_t4, 46);
    lv_obj_set_width(ui_t4, lv_pct(100));
    lv_obj_set_align(ui_t4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_t4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_t4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_t4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_t4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_t4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_t4, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_t4, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time__in3A = lv_label_create(ui_t4);
    lv_obj_set_width(ui_time__in3A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time__in3A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time__in3A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time__in3A, "00:00");
    lv_obj_add_flag(ui_time__in3A, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_time__in3A, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_time__in3A, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__in3A, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time__in3A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_time__in3A, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_time__in3A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_time__in3A, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_time__in3A, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_time__in3A, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_time__in3A, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_time__in3A, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_time__in3A, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__in3A, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_time__in3A, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_time__in3A, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_time__in3A, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_time__in4A = lv_label_create(ui_t4);
    lv_obj_set_width(ui_time__in4A, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time__in4A, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time__in4A, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time__in4A, "00:00");
    lv_obj_add_flag(ui_time__in4A, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_time__in4A, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_time__in4A, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__in4A, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time__in4A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_time__in4A, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_time__in4A, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_time__in4A, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_time__in4A, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_time__in4A, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_time__in4A, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_time__in4A, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_time__in4A, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__in4A, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_time__in4A, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_time__in4A, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_time__in4A, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_pill_Con = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_pill_Con);
    lv_obj_set_width(ui_pill_Con, 395);
    lv_obj_set_height(ui_pill_Con, lv_pct(86));
    lv_obj_set_x(ui_pill_Con, 1);
    lv_obj_set_y(ui_pill_Con, 23);
    lv_obj_set_align(ui_pill_Con, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_pill_Con, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_pill_Con, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_pill_Con, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_pill_Con, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_pill_Con);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_height(ui_Container5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container5, -395);
    lv_obj_set_y(ui_Container5, 513);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_clientalarm = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_clientalarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_clientalarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_clientalarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_clientalarm, "Client Name");
    lv_obj_add_flag(ui_clientalarm, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_clientalarm, &ui_font_kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_clientalarm, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clientalarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clientalarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clientalarm, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clientalarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_clientalarm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_clientalarm, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_clientalarm, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_clientalarm, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_clientalarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_clientalarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_clientalarm, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_clientalarm, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_clientalarm, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_clientalarm, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Pill_alarm = lv_obj_create(ui_pill_Con);
    lv_obj_remove_style_all(ui_Pill_alarm);
    lv_obj_set_height(ui_Pill_alarm, 36);
    lv_obj_set_width(ui_Pill_alarm, lv_pct(100));
    lv_obj_set_align(ui_Pill_alarm, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Pill_alarm, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Pill_alarm, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Pill_alarm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time__alarm = lv_label_create(ui_Pill_alarm);
    lv_obj_set_width(ui_time__alarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time__alarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time__alarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time__alarm, "12:00");
    lv_obj_add_flag(ui_time__alarm, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_time__alarm, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_time__alarm, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__alarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_time__alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_time__alarm, lv_color_hex(0xF732DD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_time__alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_time__alarm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_time__alarm, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_time__alarm, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_time__alarm, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_time__alarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_time__alarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_time__alarm, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_time__alarm, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_time__alarm, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_time__alarm, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_A_alarm = lv_label_create(ui_Pill_alarm);
    lv_obj_set_width(ui_A_alarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_A_alarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_A_alarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_A_alarm, "capsule");
    lv_obj_add_flag(ui_A_alarm, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_A_alarm, &ui_font_kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_A_alarm, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_A_alarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_A_alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_A_alarm, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_A_alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_A_alarm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_A_alarm, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_A_alarm, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_A_alarm, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_A_alarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_A_alarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_A_alarm, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_A_alarm, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_A_alarm, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_A_alarm, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_B_alarm = lv_label_create(ui_Pill_alarm);
    lv_obj_set_width(ui_B_alarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_B_alarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_B_alarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_B_alarm, "Paracetamol");
    lv_obj_add_flag(ui_B_alarm, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_B_alarm, &ui_font_kanit20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_B_alarm, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_B_alarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_B_alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_B_alarm, lv_color_hex(0xE5E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_B_alarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_B_alarm, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_B_alarm, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_B_alarm, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_B_alarm, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_B_alarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_B_alarm, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_B_alarm, lv_color_hex(0xF7F7F7), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_B_alarm, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_B_alarm, lv_color_hex(0xC1C1C1), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_B_alarm, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_pick_icon = lv_obj_create(ui_pill_Con);
    lv_obj_remove_style_all(ui_pick_icon);
    lv_obj_set_height(ui_pick_icon, 114);
    lv_obj_set_width(ui_pick_icon, lv_pct(100));
    lv_obj_set_x(ui_pick_icon, 164);
    lv_obj_set_y(ui_pick_icon, -10);
    lv_obj_set_align(ui_pick_icon, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_pick_icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_pick_icon, &ui_img_pickup_icon1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Pill_alarm1 = lv_obj_create(ui_pill_Con);
    lv_obj_remove_style_all(ui_Pill_alarm1);
    lv_obj_set_height(ui_Pill_alarm1, 68);
    lv_obj_set_width(ui_Pill_alarm1, lv_pct(103));
    lv_obj_set_align(ui_Pill_alarm1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Pill_alarm1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Pill_alarm1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Pill_alarm1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Pill_alarm1);
    lv_obj_set_width(ui_Button1, lv_pct(78));
    lv_obj_set_height(ui_Button1, lv_pct(93));
    lv_obj_set_x(ui_Button1, -171);
    lv_obj_set_y(ui_Button1, -8);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_Button1, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xF2A3F5), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label1 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label1, lv_pct(100));
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "กดปุ่มเพื่อรับยา");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_kanit24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setting_Con = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_setting_Con);
    lv_obj_set_width(ui_setting_Con, 395);
    lv_obj_set_height(ui_setting_Con, lv_pct(86));
    lv_obj_set_x(ui_setting_Con, 1);
    lv_obj_set_y(ui_setting_Con, 23);
    lv_obj_set_align(ui_setting_Con, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_setting_Con, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_setting_Con, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_setting_Con, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_setting_Con, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_side(ui_setting_Con, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Total_body = lv_obj_create(ui_setting_Con);
    lv_obj_remove_style_all(ui_Total_body);
    lv_obj_set_width(ui_Total_body, lv_pct(100));
    lv_obj_set_height(ui_Total_body, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Total_body, 4);
    lv_obj_set_y(ui_Total_body, -44);
    lv_obj_set_align(ui_Total_body, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Total_body, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Total_body, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_set_style_pad_left(ui_Total_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Total_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Total_body, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Total_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Total_body, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Total_body, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Total_body);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "ปริมาณยาคงเหลือ");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Total_body);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, lv_pct(100));
    lv_obj_set_height(ui_Container4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Container4, 0);
    lv_obj_set_y(ui_Container4, -1);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container6 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container6, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_A_total_lebel = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_A_total_lebel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_A_total_lebel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_A_total_lebel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_A_total_lebel, "Paracetamol");
    lv_obj_set_style_text_font(ui_A_total_lebel, &ui_font_kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_A_total_ = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_A_total_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_A_total_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_A_total_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_A_total_, "0");
    lv_obj_add_flag(ui_A_total_, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_A_total_, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_A_total_, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_A_total_, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_A_total_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_A_total_, lv_color_hex(0xD5D6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_A_total_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_A_total_, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_A_total_, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_A_total_, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_A_total_, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_A_total_, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_A_total_, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_A_total_, lv_color_hex(0xEAEAEA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_A_total_, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_A_total_, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_A_total_, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container7 = lv_obj_create(ui_Container4);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Container7, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_B_total_lebel = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_B_total_lebel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_B_total_lebel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_B_total_lebel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_B_total_lebel, "capsule");
    lv_obj_set_style_text_font(ui_B_total_lebel, &ui_font_kanit18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_B_total_ = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_B_total_, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_B_total_, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_B_total_, LV_ALIGN_CENTER);
    lv_label_set_text(ui_B_total_, "0");
    lv_obj_add_flag(ui_B_total_, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_B_total_, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_B_total_, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_B_total_, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_B_total_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_B_total_, lv_color_hex(0xD5D6D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_B_total_, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_B_total_, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_B_total_, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_B_total_, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_B_total_, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_B_total_, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_B_total_, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_B_total_, lv_color_hex(0xEAEAEA), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_B_total_, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_B_total_, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_B_total_, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Image2 = lv_img_create(ui_Total_body);
    lv_img_set_src(ui_Image2, &ui_img_smartpill_png);
    lv_obj_set_height(ui_Image2, 154);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_Image2, 816);
    lv_obj_set_y(ui_Image2, 109);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 200);

    ui_P_refresh3 = lv_btn_create(ui_Main);
    lv_obj_set_width(ui_P_refresh3, 60);
    lv_obj_set_height(ui_P_refresh3, 60);
    lv_obj_set_x(ui_P_refresh3, 161);
    lv_obj_set_y(ui_P_refresh3, 122);
    lv_obj_set_align(ui_P_refresh3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_P_refresh3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_P_refresh3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_P_refresh3, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_P_refresh3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_P_refresh3, &ui_img_312035399, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_P_refresh3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_P_refresh3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_P_refresh3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_P_refresh3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Top = lv_obj_create(ui_Index);
    lv_obj_set_height(ui_Top, 45);
    lv_obj_set_width(ui_Top, lv_pct(85));
    lv_obj_set_x(ui_Top, 6);
    lv_obj_set_y(ui_Top, 0);
    lv_obj_set_align(ui_Top, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_Top, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Top, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Top, lv_color_hex(0x61A9F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Top, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Top, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi_icon = lv_obj_create(ui_Top);
    lv_obj_remove_style_all(ui_Wifi_icon);
    lv_obj_set_width(ui_Wifi_icon, 69);
    lv_obj_set_height(ui_Wifi_icon, 50);
    lv_obj_set_x(ui_Wifi_icon, 16);
    lv_obj_set_y(ui_Wifi_icon, -1);
    lv_obj_set_align(ui_Wifi_icon, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Wifi_icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Wifi_icon, &ui_img_1272477160, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_Wifi_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_Wifi_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cloud_icon = lv_obj_create(ui_Top);
    lv_obj_remove_style_all(ui_cloud_icon);
    lv_obj_set_width(ui_cloud_icon, 69);
    lv_obj_set_height(ui_cloud_icon, 50);
    lv_obj_set_x(ui_cloud_icon, -35);
    lv_obj_set_y(ui_cloud_icon, 1);
    lv_obj_set_align(ui_cloud_icon, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_cloud_icon, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_cloud_icon, &ui_img_1024313544, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor(ui_cloud_icon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_recolor_opa(ui_cloud_icon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time_Label = lv_label_create(ui_Top);
    lv_obj_set_width(ui_time_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_time_Label, "12:34:56");
    lv_obj_set_style_text_color(ui_time_Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time_Label, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loading = lv_obj_create(ui_Index);
    lv_obj_set_width(ui_loading, lv_pct(100));
    lv_obj_set_height(ui_loading, lv_pct(100));
    lv_obj_set_align(ui_loading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loading, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_loading, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_loading, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loading, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_loading, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner = lv_spinner_create(ui_loading, 1000, 90);
    lv_obj_set_width(ui_Spinner, 100);
    lv_obj_set_height(ui_Spinner, 100);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_Spinner, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Spinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Spinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Spinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Spinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Spinner, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0x61A9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Home_btn, ui_event_Home_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_switch_btn, ui_event_switch_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pill_btn, ui_event_Pill_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setting_btn, ui_event_Setting_btn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_P_refresh3, ui_event_P_refresh3, LV_EVENT_ALL, NULL);

}
