// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LED

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Index
void ui_Index_screen_init(void);
lv_obj_t * ui_Index;
lv_obj_t * ui_Body;
lv_obj_t * ui_Menu_Box;
void ui_event_Home_btn(lv_event_t * e);
lv_obj_t * ui_Home_btn;
void ui_event_switch_btn(lv_event_t * e);
lv_obj_t * ui_switch_btn;
void ui_event_Pill_btn(lv_event_t * e);
lv_obj_t * ui_Pill_btn;
void ui_event_Setting_btn(lv_event_t * e);
lv_obj_t * ui_Setting_btn;
lv_obj_t * ui_Main;
lv_obj_t * ui_home_Con;
lv_obj_t * ui_home_layout;
lv_obj_t * ui_status_layout;
lv_obj_t * ui_Label3;
lv_obj_t * ui_temp_box;
lv_obj_t * ui_temp_Label;
lv_obj_t * ui_Container8;
lv_obj_t * ui_temp_Label_value;
lv_obj_t * ui_temp_Label_value1;
lv_obj_t * ui_Humi_box;
lv_obj_t * ui_humi_Label;
lv_obj_t * ui_Container9;
lv_obj_t * ui_humi_Label_value;
lv_obj_t * ui_humi_Label_value1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_P_name;
lv_obj_t * ui_P_refresh;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Container3;
lv_obj_t * ui_switch1_select1;
lv_obj_t * ui_Label15;
lv_obj_t * ui_switch2_select1;
lv_obj_t * ui_Label16;
lv_obj_t * ui_switch3_select1;
lv_obj_t * ui_Label17;
lv_obj_t * ui_switch4_select1;
lv_obj_t * ui_Label18;
lv_obj_t * ui_switch_Con;
lv_obj_t * ui_pill_type_box;
lv_obj_t * ui_Label5;
lv_obj_t * ui_type_sele;
void ui_event_type_a(lv_event_t * e);
lv_obj_t * ui_type_a;
lv_obj_t * ui_A_Label;
lv_obj_t * ui_timer_bodyA;
lv_obj_t * ui_r12_label3;
lv_obj_t * ui_Checkbox1A;
lv_obj_t * ui_Checkbox2A;
lv_obj_t * ui_t3;
lv_obj_t * ui_time__in1A;
lv_obj_t * ui_time__in2A;
lv_obj_t * ui_r12_label4;
lv_obj_t * ui_Checkbox3A;
lv_obj_t * ui_Checkbox4A;
lv_obj_t * ui_t4;
lv_obj_t * ui_time__in3A;
lv_obj_t * ui_time__in4A;
lv_obj_t * ui_pill_Con;
lv_obj_t * ui_Container5;
lv_obj_t * ui_clientalarm;
lv_obj_t * ui_Pill_alarm;
lv_obj_t * ui_time__alarm;
lv_obj_t * ui_A_alarm;
lv_obj_t * ui_B_alarm;
lv_obj_t * ui_pick_icon;
lv_obj_t * ui_Pill_alarm1;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_setting_Con;
lv_obj_t * ui_Total_body;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Container6;
lv_obj_t * ui_A_total_lebel;
lv_obj_t * ui_A_total_;
lv_obj_t * ui_Container7;
lv_obj_t * ui_B_total_lebel;
lv_obj_t * ui_B_total_;
lv_obj_t * ui_Image2;
void ui_event_P_refresh3(lv_event_t * e);
lv_obj_t * ui_P_refresh3;
lv_obj_t * ui_Top;
lv_obj_t * ui_Wifi_icon;
lv_obj_t * ui_cloud_icon;
lv_obj_t * ui_time_Label;
lv_obj_t * ui_loading;
lv_obj_t * ui_Spinner;


// SCREEN: ui_loading_page
void ui_loading_page_screen_init(void);
lv_obj_t * ui_loading_page;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Image1;
void ui_event_P_refresh4(lv_event_t * e);
lv_obj_t * ui_P_refresh4;
lv_obj_t * ui____initial_actions0;
const lv_img_dsc_t * ui_imgset_pickup_icon[1] = {&ui_img_pickup_icon1_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Home_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_home_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_switch_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Home_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_switch_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Pill_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Setting_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_setting_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_pill_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Setting_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Pill_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_switch_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_home_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_switch_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_state_modify(ui_Home_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_setting_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_pill_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Setting_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Pill_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_Pill_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_pill_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_home_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_switch_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_setting_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Pill_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Home_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Setting_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_Setting_btn(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_setting_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_home_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_pill_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_switch_Con, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_state_modify(ui_Setting_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_Home_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_switch_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Pill_btn, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_type_a(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_type_a, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_flag_modify(ui_timer_bodyA, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_Button1, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}
void ui_event_P_refresh3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_loading_page, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_loading_page_screen_init);
    }
}
void ui_event_P_refresh4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Index, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Index_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Index_screen_init();
    ui_loading_page_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Index);
}
