// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: LED

#ifndef _LED_UI_H
#define _LED_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Index
void ui_Index_screen_init(void);
extern lv_obj_t * ui_Index;
extern lv_obj_t * ui_Body;
extern lv_obj_t * ui_Menu_Box;
void ui_event_Home_btn(lv_event_t * e);
extern lv_obj_t * ui_Home_btn;
void ui_event_switch_btn(lv_event_t * e);
extern lv_obj_t * ui_switch_btn;
void ui_event_Pill_btn(lv_event_t * e);
extern lv_obj_t * ui_Pill_btn;
void ui_event_Setting_btn(lv_event_t * e);
extern lv_obj_t * ui_Setting_btn;
extern lv_obj_t * ui_Main;
extern lv_obj_t * ui_home_Con;
extern lv_obj_t * ui_home_layout;
extern lv_obj_t * ui_status_layout;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_temp_box;
extern lv_obj_t * ui_temp_Label;
extern lv_obj_t * ui_temp_Label_value;
extern lv_obj_t * ui_Humi_box;
extern lv_obj_t * ui_humi_Label;
extern lv_obj_t * ui_humi_Label_value;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_P_name;
extern lv_obj_t * ui_P_refresh;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_switch1_select1;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_switch2_select1;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_switch3_select1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_switch4_select1;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_switch_Con;
extern lv_obj_t * ui_pill_type_box;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_type_sele;
void ui_event_type_a(lv_event_t * e);
extern lv_obj_t * ui_type_a;
extern lv_obj_t * ui_A_Label;
void ui_event_type_b(lv_event_t * e);
extern lv_obj_t * ui_type_b;
extern lv_obj_t * ui_B_Label;
extern lv_obj_t * ui_timer_bodyA;
extern lv_obj_t * ui_r12_label3;
extern lv_obj_t * ui_Checkbox1A;
extern lv_obj_t * ui_Checkbox2A;
extern lv_obj_t * ui_t3;
extern lv_obj_t * ui_time__in1A;
extern lv_obj_t * ui_time__in2A;
extern lv_obj_t * ui_r12_label4;
extern lv_obj_t * ui_Checkbox3A;
extern lv_obj_t * ui_Checkbox4A;
extern lv_obj_t * ui_t4;
extern lv_obj_t * ui_time__in3A;
extern lv_obj_t * ui_time__in4A;
extern lv_obj_t * ui_Redo_box2;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_DayA_Container;
extern lv_obj_t * ui_A1_enable;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_A2_enable;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_A3_enable;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_A4_enable;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_A5_enable;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_A6_enable;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_A7_enable;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_timer_bodyB;
extern lv_obj_t * ui_r12_label1;
extern lv_obj_t * ui_Checkbox1B;
extern lv_obj_t * ui_Checkbox2B;
extern lv_obj_t * ui_t1;
extern lv_obj_t * ui_time__in1B;
extern lv_obj_t * ui_time__in2B;
extern lv_obj_t * ui_r12_label2;
extern lv_obj_t * ui_Checkbox3B;
extern lv_obj_t * ui_Checkbox4B;
extern lv_obj_t * ui_t2;
extern lv_obj_t * ui_time__in3B;
extern lv_obj_t * ui_time__in4B;
extern lv_obj_t * ui_Redo_box1;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_DayB_Container;
extern lv_obj_t * ui_B1_enable;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_B2_enable;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_B3_enable;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_B4_enable;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_B5_enable;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_B6_enable;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_B7_enable;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_pill_Con;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_P_name2;
extern lv_obj_t * ui_P_refresh2;
extern lv_obj_t * ui_Pill_alarm;
extern lv_obj_t * ui_time__alarm;
extern lv_obj_t * ui_A_alarm;
extern lv_obj_t * ui_B_alarm;
extern lv_obj_t * ui_pick_icon;
extern lv_obj_t * ui_Pill_alarm1;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_setting_Con;
extern lv_obj_t * ui_Total_body;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_A_total_lebel;
extern lv_obj_t * ui_A_total_;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_B_total_lebel;
extern lv_obj_t * ui_B_total_;
extern lv_obj_t * ui_Image2;
void ui_event_P_refresh3(lv_event_t * e);
extern lv_obj_t * ui_P_refresh3;
extern lv_obj_t * ui_Top;
extern lv_obj_t * ui_Wifi_icon;
extern lv_obj_t * ui_cloud_icon;
extern lv_obj_t * ui_time_Label;
extern lv_obj_t * ui_loading;
extern lv_obj_t * ui_Spinner;
// SCREEN: ui_loading_page
void ui_loading_page_screen_init(void);
extern lv_obj_t * ui_loading_page;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Image1;
void ui_event_P_refresh4(lv_event_t * e);
extern lv_obj_t * ui_P_refresh4;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_685164422);    // assets/home-icon.png
LV_IMG_DECLARE(ui_img_alarm_png);    // assets/alarm.png
LV_IMG_DECLARE(ui_img_pill_png);    // assets/pill.png
LV_IMG_DECLARE(ui_img_setting_png);    // assets/setting.png
LV_IMG_DECLARE(ui_img_312035399);    // assets/redo-arrow-icon.png
LV_IMG_DECLARE(ui_img_pickup_icon1_png);    // assets/pickup_icon1.png
LV_IMG_DECLARE(ui_img_smartpill_png);    // assets/SmartPill.png
LV_IMG_DECLARE(ui_img_1345796492);    // assets/globe-icon.png
LV_IMG_DECLARE(ui_img_1272477160);    // assets/wifi-icon.png
LV_IMG_DECLARE(ui_img_1024313544);    // assets/cloud-icon.png



LV_FONT_DECLARE(ui_font_kanit18);
LV_FONT_DECLARE(ui_font_kanit20);
LV_FONT_DECLARE(ui_font_kanit24);



void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
